name: Automation Tests - Swivel Tech

on:
  workflow_dispatch:
  workflow_run:
    workflows: 
      - "Tech Frontend - Automatically Build and Deploy to Stage Amazon Lightsail"
      - "Tech Frontend - Manually Build and Deploy to Stage Amazon Lightsail"
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm install
          
      - name: Install Allure
        run: npm install -g allure-commandline

      # - name: Install Chrome
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y google-chrome-stable

      # - name: Verify Chrome Installation
      #   run: google-chrome --version

      - name: Run WebdriverIO Tests
        run: npm run swiveltech

      #- name: Find and Save Report Path
      #  run: |
      #    allure generate --clean --single-file allure-results
       # run: |
       #   allure generate ./reports/allure-results --clean -o ./reports
       #   ls reports/
          
      - name: Generate Timestamp
        shell: pwsh
        run: |
          $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
          echo "TIMESTAMP=$timestamp" >> $env:GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEV_GITHUB_ACTION_ROLE }}
          aws-region: ap-southeast-2

      - name: Upload Report to S3
        shell: pwsh
        run: |
          Rename-Item -Path allure-report/index.html -NewName "index-$env:TIMESTAMP.html"
          aws s3 cp allure-report/index-$env:TIMESTAMP.html s3://internal-test-automation/swivel-tech/
