name: Automation Tests - Swivel Group

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps

      # - name: Fix Npm issues
      #   run: |
      #     npm audit fix --force

      - name: Install Allure
        run: npm install -g allure-commandline

      # - name: Install Chrome
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y google-chrome-stable

      # - name: Verify Chrome Installation
      #   run: google-chrome --version

      - name: Run WebdriverIO Tests
        run: npm run swivelgroup

      #- name: Find and Save Report Path
      #  run: |
      #    allure generate --clean --single-file allure-results
      # run: |
      #   allure generate ./reports/allure-results --clean -o ./reports
      #   ls reports/

      - name: Generate Timestamp
        shell: pwsh
        run: |
          $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
          echo "TIMESTAMP=$timestamp" >> $env:GITHUB_ENV

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEV_GITHUB_ACTION_ROLE }}
          aws-region: ap-southeast-2

      - name: Upload Report to S3
        shell: pwsh
        run: |
          Rename-Item -Path allure-report/index.html -NewName "index-$env:TIMESTAMP.html"
          aws s3 cp allure-report/index-$env:TIMESTAMP.html s3://internal-test-automation/swivel-group/

      - name: Send Report via AWS SES
        shell: pwsh
        run: |
          $REPORT_URL="https://internal-test-automation.s3.ap-southeast-2.amazonaws.com/swivel-group/index-$env:TIMESTAMP.html"

          $htmlContent = "<html><body><h2>Automation Test Report - SwivelGroup</h2><p>Click <a href=""$REPORT_URL"">here</a> to view the report.</p></body></html>"

          $messageObj = @{
            Subject = @{ Data = "Automation Test Report - SwivelGroup" }
            Body = @{
              Text = @{ Data = "Here is your test report: $REPORT_URL" }
              Html = @{ Data = $htmlContent }
            }
          }

          $messageJson = ConvertTo-Json -Depth 4 -Compress $messageObj

          aws ses send-email --from "serviceaccount@swivelgroup.com.au" --destination "ToAddresses=dilshan@swivelgroup.com.au" --message $messageJson --region "ap-southeast-2"
