name: Automation Tests

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install
          ls

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Verify Chrome Installation
        run: google-chrome --version

      - name: Run WebdriverIO Tests with Console Logs
        run: |
          npm run web

      - name: Find and Save Report Path
        run: |
          cd reports/
          allure generate --clean --single-file allure-results
          cat index.html
